name: on_ticos_framework_publish
run-name: ${{ github.actor }} is publishing the codegen path ğŸš€
on:
  push:
    tags:
      - 'v*'
jobs:
  publish-codegen:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@master
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Compress codegen
        run: |
          echo "ğŸ–¥ï¸ The workflow is now ready to compress codegen and move it to the project root path."
          cd scripts
          zip -r codegen.zip codegen
          mv codegen.zip ../
          cd -
      - run: echo "ğŸš€ create release"
      - name: Create release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - run: echo "ğŸš€ upload release"
      - name: Upload Release Asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./codegen.zip
          asset_name: codegen.zip
      - name: Cleanup
        run: rm codegen.zip
      - run: echo "ğŸ This job's status is ${{ job.status }}."
